services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: hada
      POSTGRES_USER: hada
      POSTGRES_PASSWORD: hada
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hada

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hada

volumes:
  pgdata:

networks:
  hada:
    name: hada
    driver: bridge
